In [1]:
#importing json file 
import json
with open('geocodinglogfle.json', 'r') as f:
    json_list = json.load(f)

In [2]:
len(json_list)

25010

In [3]:
#creating a pandas dataframe with the required columns
import pandas as pd
data = pd.DataFrame(columns=['api_formatted_address','api_lat','api_lng','location_type','api_json_resp'])

In [4]:
#creating a set to hold exceptions and setting the range for loop
z=len(json_list)
y =set()
m = z-1
m

25009

In [5]:
#getting the required data traversing through the loop
for i in range(m):
    try:
        x=json_list[i]
        obj1 = x['results']
        obj2 = obj1[0]['address_components']
        formatted_address = obj1[0]['formatted_address']
        obj3 = obj1[0]['geometry']
        location_type = obj3['location_type']
        obj4 = obj3['location']
        latitude = obj4['lat']
        longitude = obj4['lng']
        data = data.append({'api_formatted_address':formatted_address,'api_lat':latitude,'api_lng':longitude,'location_type':location_type,'api_json_resp':obj1},ignore_index=True)
    except:
        y = json_list[i]

In [12]:
data.head(25)

,api_formatted_address,api_lat,api_lng,location_type,api_json_resp
0,"Serangoon, Singapore",1.355357,103.867871,APPROXIMATE,[{'address_components': [{'long_name': 'Serang...
1,"100 Bukit Timah Rd, Singapore 229899",1.310727,103.846837,ROOFTOP,"[{'address_components': [{'long_name': '100', ..."
2,Singapore 821165,1.395055,103.914852,APPROXIMATE,[{'address_components': [{'long_name': '821165...
3,"270 Yishun Street 22, Singapore 760270",1.437374,103.839874,ROOFTOP,"[{'address_components': [{'long_name': '270', ..."
4,Singapore 380018,1.314735,103.871939,APPROXIMATE,[{'address_components': [{'long_name': '380018...
5,"53 Upper Serangoon View, Singapore",1.376283,103.903244,ROOFTOP,"[{'address_components': [{'long_name': '53', '..."
6,"793 Yishun Ring Rd, Singapore 760793",1.420571,103.831700,ROOFTOP,"[{'address_components': [{'long_name': '793', ..."
7,"141 Serangoon North Ave 2, 11 Block 141, Singa...",1.368570,103.874486,ROOFTOP,"[{'address_components': [{'long_name': '11', '..."
8,"145 Lor 2 Toa Payoh, Singapore 310145 Lor 2 To...",1.335094,103.846175,ROOFTOP,[{'address_components': [{'long_name': '145 Lo...
9,"614B Edgefield Plains, Singapore 822614",1.402914,103.910170,ROOFTOP,"[{'address_components': [{'long_name': '614B',..."
10,"286A Toh Guan Rd, Singapore 601286",1.338922,103.745594,ROOFTOP,"[{'address_components': [{'long_name': '286A',..."
11,"228 Sumang Lane, 13, Singapore",1.402513,103.892257,RANGE_INTERPOLATED,"[{'address_components': [{'long_name': '13', '..."
12,Singapore 768828,1.423798,103.838436,APPROXIMATE,[{'address_components': [{'long_name': '768828...
13,"36 Commerce Rd, Peterborough PE2 6LR, UK",52.551222,-0.319489,ROOFTOP,"[{'address_components': [{'long_name': '36', '..."
14,"Orton Waterville, Peterborough PE2 6WZ, UK",52.552225,-0.315160,GEOMETRIC_CENTER,[{'address_components': [{'long_name': 'Orton ...
15,"Park House, Peterborough Business Park, Lynch ...",52.552615,-0.317017,GEOMETRIC_CENTER,[{'address_components': [{'long_name': 'Park H...
16,"22 Buttercream Dr, Peterborough PE2 9SW, UK",52.560468,-0.260277,RANGE_INTERPOLATED,"[{'address_components': [{'long_name': '22', '..."
17,"Peterborough Business Park, Lynch Wood, Peterb...",52.550119,-0.324447,ROOFTOP,[{'address_components': [{'long_name': 'Peterb...
18,"Tyndall Court, Lynch Wood, Peterborough PE2 6L...",52.551605,-0.320452,GEOMETRIC_CENTER,[{'address_components': [{'long_name': 'Tyndal...
19,"SpeestraÃŸe 6, 40885 Ratingen, Germany",51.333748,6.832026,ROOFTOP,"[{'address_components': [{'long_name': '6', 's..."
20,"Bouwstraat 55, 3572 SP Utrecht, Netherlands",52.096816,5.132322,ROOFTOP,"[{'address_components': [{'long_name': '55', '..."
21,"Utrecht, Netherlands",52.090737,5.121420,APPROXIMATE,[{'address_components': [{'long_name': 'Utrech...
22,"Catharijnesingel 33, 3511 GC Utrecht, Netherlands",52.091263,5.112514,ROOFTOP,"[{'address_components': [{'long_name': '33', '..."
23,"Laan van Puntenburg 102, 3511 ER Utrecht, Neth...",52.087881,5.113617,RANGE_INTERPOLATED,"[{'address_components': [{'long_name': '102', ..."
24,"Voorstraat, 3512 AR Utrecht, Netherlands",52.095110,5.120991,GEOMETRIC_CENTER,[{'address_components': [{'long_name': 'Voorst...

In [6]:
y

{'results': [], 'status': 'ZERO_RESULTS'}

In [10]:
export_excel = data.to_excel (r'D:\export_dataframe.xlsx', index = None, header=True)